services:
  
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_agendamento
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Cavalo24123#
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql 


  app-agendamento:
    build: .
    container_name: app_agendamento_container
    depends_on:
      - database


volumes:
  sql_data: